name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rust-build-artifacts
        path: target

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download a build artifact
      uses: actions/download-artifact@v3
      with:
        name: rust-build-artifacts

    - name: Run tests
      run: cargo test --verbose